# SPDX-License-Identifier: GPL-3.0-only
# Copyright (c) 2026 WorkMesh contributors

[Service]
Environment=GOMEMLIMIT=128MiB
Environment=GOGC=50
MemoryAccounting=yes
MemoryHigh=192M
MemoryMax=256M
MemorySwapMax=64M
