// SPDX-License-Identifier: GPL-3.0-only
// Copyright (c) 2026 WorkMesh contributors

package api

// registerLegacyHostsRoutes 注册 hosts 领域尚未迁移的兼容路由。
func registerLegacyHostsRoutes(mux routeRegistrar) {
	mux.HandleFunc("GET /api/v2/hosts/diagnostics/goroutines", fallbackRouteHandler)
	mux.HandleFunc("GET /api/v2/hosts/diagnostics/summary", fallbackRouteHandler)
	mux.HandleFunc("GET /api/v2/hosts/disks", fallbackRouteHandler)
	mux.HandleFunc("GET /api/v2/hosts/firewall/rules/sync/task", fallbackRouteHandler)
	mux.HandleFunc("GET /api/v2/hosts/firewall/settings", fallbackRouteHandler)
	mux.HandleFunc("GET /api/v2/hosts/monitor/iooptions", fallbackRouteHandler)
	mux.HandleFunc("GET /api/v2/hosts/monitor/netoptions", fallbackRouteHandler)
	mux.HandleFunc("GET /api/v2/hosts/monitor/setting", fallbackRouteHandler)
	mux.HandleFunc("GET /api/v2/hosts/terminal/container", fallbackRouteHandler)
	mux.HandleFunc("GET /api/v2/hosts/terminal/local", fallbackRouteHandler)
	mux.HandleFunc("GET /api/v2/hosts/terminal/ssh", fallbackRouteHandler)
	mux.HandleFunc("GET /api/v2/hosts/tool/supervisor/process", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/hosts/del", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/hosts/diagnostics/profiles", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/hosts/firewall/base", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/hosts/firewall/filter/operate", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/hosts/firewall/operate", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/hosts/firewall/rules", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/hosts/firewall/rules/check", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/hosts/firewall/rules/delete", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/hosts/firewall/rules/native/detail", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/hosts/firewall/rules/reorder", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/hosts/firewall/rules/reset", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/hosts/firewall/rules/search", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/hosts/firewall/rules/sync", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/hosts/firewall/rules/sync/preview", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/hosts/firewall/rules/update", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/hosts/firewall/settings/operate", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/hosts/info", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/hosts/monitor/clean", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/hosts/monitor/search", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/hosts/monitor/setting/update", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/hosts/search", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/hosts/ssh/log", loadSSHLogs)
	mux.HandleFunc("POST /api/v2/hosts/ssh/log/clean", cleanSSHLogs)
	mux.HandleFunc("POST /api/v2/hosts/ssh/log/export", exportSSHLogs)
	mux.HandleFunc("POST /api/v2/hosts/test/byid", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/hosts/test/byinfo", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/hosts/tool/config/get", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/hosts/tool/config/set", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/hosts/tool/init", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/hosts/tool/operate", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/hosts/tool/status", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/hosts/tool/supervisor/process", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/hosts/tool/supervisor/process/file", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/hosts/tool/supervisor/process/file/get", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/hosts/tree", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/hosts/update", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/hosts/update/group", fallbackRouteHandler)
}
