// SPDX-License-Identifier: GPL-3.0-only
// Copyright (c) 2026 WorkMesh contributors

package api

// registerLegacyContainersRoutes 注册 containers 领域尚未迁移的兼容路由。
func registerLegacyContainersRoutes(mux routeRegistrar) {
	mux.HandleFunc("GET /api/v2/containers/daemonjson", fallbackRouteHandler)
	mux.HandleFunc("GET /api/v2/containers/daemonjson/file", fallbackRouteHandler)
	mux.HandleFunc("GET /api/v2/containers/image", fallbackRouteHandler)
	mux.HandleFunc("GET /api/v2/containers/image/all", fallbackRouteHandler)
	mux.HandleFunc("GET /api/v2/containers/limit", fallbackRouteHandler)
	mux.HandleFunc("GET /api/v2/containers/list/stats", fallbackRouteHandler)
	mux.HandleFunc("GET /api/v2/containers/network", fallbackRouteHandler)
	mux.HandleFunc("GET /api/v2/containers/repo", fallbackRouteHandler)
	mux.HandleFunc("GET /api/v2/containers/search/log", fallbackRouteHandler)
	mux.HandleFunc("GET /api/v2/containers/stats/:id", fallbackRouteHandler)
	mux.HandleFunc("GET /api/v2/containers/status", fallbackRouteHandler)
	mux.HandleFunc("GET /api/v2/containers/template", fallbackRouteHandler)
	mux.HandleFunc("GET /api/v2/containers/volume", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/clean/log", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/commit", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/compose", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/compose/clean/log", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/compose/env", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/compose/operate", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/compose/pin", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/compose/search", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/compose/test", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/compose/update", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/daemonjson/update", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/daemonjson/update/byfile", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/docker/operate", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/download/log", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/files/content", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/files/del", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/files/download", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/files/search", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/files/size", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/files/upload", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/image/build", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/image/load", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/image/pull", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/image/push", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/image/remove", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/image/save", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/image/search", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/image/tag", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/info", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/inspect", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/ipv6option/update", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/item/stats", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/list", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/list/byimage", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/logoption/update", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/network", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/network/del", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/network/search", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/prune", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/rename", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/repo", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/repo/del", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/repo/search", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/repo/status", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/repo/update", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/search", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/template", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/template/batch", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/template/del", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/template/search", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/template/update", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/update", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/upgrade", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/users", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/volume", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/volume/del", fallbackRouteHandler)
	mux.HandleFunc("POST /api/v2/containers/volume/search", fallbackRouteHandler)
}
