// SPDX-License-Identifier: GPL-3.0-only
// Copyright (c) 2026 WorkMesh contributors

package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestScanBoundaries 验证文件和函数在边界值处通过，超过一行即失败。
func TestScanBoundaries(t *testing.T) {
	root := t.TempDir()
	writeSource(t, root, "boundary.go", "package boundary\n// 边界函数说明\nfunc Boundary() {\n"+strings.Repeat("\t_ = 1\n", 78)+"}\n")
	writeSource(t, root, "long.go", "package boundary\n// 长函数说明\nfunc Long() {\n"+strings.Repeat("\t_ = 1\n", 79)+"}\n")
	writeSource(t, root, "file.go", "package boundary\n// 文件说明\nfunc File() {}\n"+strings.Repeat("\n", 497))
	writeSource(t, root, "over.go", "package boundary\n// 文件说明\nfunc Over() {}\n"+strings.Repeat("\n", 498))
	report, err := scanRoot(root)
	if err != nil {
		t.Fatal(err)
	}
	if report.Status != "fail" || report.Counts["function_lines"] != 1 || report.Counts["file_lines"] != 1 {
		t.Fatalf("边界违规未被发现: %+v", report)
	}
}

// TestScanChineseDocAndAnonymous 验证紧邻中文说明、匿名函数和无中文说明的具名函数。
func TestScanChineseDocAndAnonymous(t *testing.T) {
	root := t.TempDir()
	writeSource(t, root, "docs.go", "package docs\n// 有中文说明\nfunc Good() { _ = func() {} }\nfunc Bad() {}\n// 不紧邻说明\n\nfunc Detached() {}\n// English only\nfunc English() {}\n")
	report, err := scanRoot(root)
	if err != nil {
		t.Fatal(err)
	}
	if report.Functions != 5 || report.Counts["chinese_doc"] != 3 {
		t.Fatalf("中文说明或匿名函数计数错误: %+v", report)
	}
}

// TestAnonymousLengthAndParseErrors 验证匿名函数超长和无效语法也会阻断门禁。
func TestAnonymousLengthAndParseErrors(t *testing.T) {
	root := t.TempDir()
	writeSource(t, root, "anonymous.go", "package example\nvar callback = func() {\n"+strings.Repeat("_ = 1\n", 79)+"}\n")
	writeSource(t, root, "broken.go", "package example\nfunc Broken(\n")
	report, err := scanRoot(root)
	if err != nil || report.Counts["function_lines"] != 1 || report.Counts["parse_error"] != 1 {
		t.Fatalf("匿名函数或解析错误未被发现: %+v, %v", report, err)
	}
}

// TestGeneratedMarkerRules 验证跨行伪标记、字符串和普通文件名不会触发生成豁免。
func TestGeneratedMarkerRules(t *testing.T) {
	for _, source := range []string{
		"// Code generated by tool\n// DO NOT EDIT.\npackage example\n",
		"package example\nvar text = `// Code generated by tool. DO NOT EDIT.`\n",
		"// 历史生成文件\npackage example\n",
	} {
		if isGeneratedSource([]byte(source)) {
			t.Fatalf("错误豁免: %q", source)
		}
	}
}

// TestScanGeneratedSource 验证标准生成标记跳过整文件且不把它视为历史豁免。
func TestScanGeneratedSource(t *testing.T) {
	root := t.TempDir()
	contents := "// Code generated by tool. DO NOT EDIT.\npackage generated\n" + strings.Repeat("\n", 600)
	writeSource(t, root, "generated.go", contents)
	report, err := scanRoot(root)
	if err != nil {
		t.Fatal(err)
	}
	if len(report.SkippedFiles) != 1 || report.Files != 0 || len(report.Violations) != 0 {
		t.Fatalf("生成文件未正确豁免: %+v", report)
	}
}

// TestScanErrors 验证不存在目录和无 Go 文件时返回扫描错误。
func TestScanErrors(t *testing.T) {
	if _, err := scanRoot(filepath.Join(t.TempDir(), "missing")); err == nil {
		t.Fatal("不存在目录应返回错误")
	}
	if _, err := scanRoot(t.TempDir()); err == nil {
		t.Fatal("无 Go 文件应返回错误")
	}
}

// writeSource 创建测试源码，不触碰项目跟踪文件。
func writeSource(t *testing.T, root, name, contents string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(root, name), []byte(contents), 0600); err != nil {
		t.Fatal(err)
	}
}
