#!/usr/bin/env sh
set -eu

WAF_ROOT="${WORKMESH_WAF_ROOT:-/opt/workmesh/waf}"
GENERATED_DIR="${WAF_ROOT}/generated"

write_if_missing() {
    path="$1"
    content="$2"
    if [ -e "$path" ]; then
        return 0
    fi
    tmp="${path}.tmp.$$"
    printf '%s' "$content" >"$tmp"
    mv "$tmp" "$path"
}

mkdir -p \
    "${WAF_ROOT}/cache" \
    "${WAF_ROOT}/data/ip-groups" \
    "${WAF_ROOT}/logs" \
    "${GENERATED_DIR}"

write_if_missing "${GENERATED_DIR}/modsecurity-mode.conf" "# WorkMesh default mode
SecRuleEngine DetectionOnly
"

write_if_missing "${GENERATED_DIR}/custom-rules.conf" "# WorkMesh custom rules are generated by the control plane.
"

write_if_missing "${GENERATED_DIR}/standard-rules.conf" "# WorkMesh standard CRS rules enabled
Include /etc/workmesh-waf/crs/crs-setup.conf
Include /etc/workmesh-waf/crs/rules/*.conf
"

write_if_missing "${GENERATED_DIR}/global-rules.conf" "# WorkMesh global rules are generated by the control plane.
"

if [ "$#" -eq 0 ]; then
    set -- /usr/local/openresty/nginx/sbin/nginx -g "daemon off;"
fi

case "$1" in
    -*)
        set -- /usr/local/openresty/nginx/sbin/nginx "$@"
        ;;
esac

exec "$@"
